jdk:
  - openjdk17

before_install:
  - yes | sdkmanager --licenses

install:
  - chmod +x ./jitpack.sh
  - ./jitpack.sh
  - pwd
  - ls -la android/ffmpeg-kit-android-lib/build/outputs/aar
  - mkdir -p published
  - cp android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar published/

artifacts:
  - path: published/ffmpeg-kit-release.aar
    type: aar
