jdk:
  - openjdk17

before_install:
  - yes | sdkmanager --licenses

install:
  - chmod +x ./jitpack.sh
  - ./jitpack.sh
  - pwd
  - ls -la prebuilt/bundle-android-aar/ffmpeg-kit/
  - ls -la android/ffmpeg-kit-android-lib/build/outputs/aar

artifacts:
  - path: android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar
    type: aar
