jdk:
  - openjdk17

before_install:
  - yes | sdkmanager --licenses

install:
  - chmod +x ./jitpack.sh
  - ./jitpack.sh

artifacts:
  - path: ./android/ffmpeg-kit-android-lib/build/outputs/aar/ffmpeg-kit-release.aar
    type: aar
