jdk:
  - openjdk17

before_install:
  - yes | sdkmanager --licenses

install:
  - chmod +x ./jitpack.sh
  - ./jitpack.sh
  - pwd
  - ls -la prebuilt/bundle-android-aar/ffmpeg-kit/

artifacts:
  - path: prebuilt/bundle-android-aar/ffmpeg-kit/ffmpeg-kit.aar
    type: aar
